from typing import Literal, Optional
from pydantic import BaseModel, Field


class ToolArgs(BaseModel):
    """Arguments for a tool call."""
    cmd: str = Field(..., description="The CLI command to execute")


class ToolRequest(BaseModel):
    """
    Structured request for tool execution.

    Generated by the Compiler agent and validated before execution.
    """
    action: Literal["CALL_TOOL"] = Field(
        default="CALL_TOOL",
        description="Action type - always CALL_TOOL for CLI execution"
    )
    tool: Literal["run_cli"] = Field(
        default="run_cli",
        description="Tool name - run_cli for command execution"
    )
    args: ToolArgs = Field(..., description="Tool arguments containing the command")

    class Config:
        json_schema_extra = {
            "example": {
                "action": "CALL_TOOL",
                "tool": "run_cli",
                "args": {"cmd": "ls -la"}
            }
        }


class ToolResult(BaseModel):
    """Result from executing a CLI command."""
    cmd: str = Field(..., description="The command that was executed")
    exit_code: int = Field(..., description="Exit code from the command")
    stdout: str = Field(default="", description="Standard output from the command")
    stderr: str = Field(default="", description="Standard error from the command")

    @property
    def success(self) -> bool:
        """Check if the command executed successfully."""
        return self.exit_code == 0

    def format_for_llm(self) -> str:
        """Format the result for inclusion in LLM context."""
        output = f"Command: {self.cmd}\nExit Code: {self.exit_code}\n"
        if self.stdout:
            output += f"Output:\n{self.stdout}\n"
        if self.stderr:
            output += f"Errors:\n{self.stderr}\n"
        return output
