version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jarvis-api
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/jarvis
      - OPENAI_API_KEY=
    depends_on:
      - mongodb
    networks:
      - jarvis-network

  mongodb:
    image: mongo:7.0
    container_name: jarvis-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=jarvis
    volumes:
      - mongodb_data:/data/db
    networks:
      - jarvis-network

volumes:
  mongodb_data:
    driver: local

networks:
  jarvis-network:
    driver: bridge